### 1_tensorflow2.0


In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import datasets

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)


2.0.0-alpha0
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
matplotlib 3.1.0
numpy 1.16.4
pandas 0.24.2
sklearn 0.21.2
tensorflow 2.0.0-alpha0
tensorflow.python.keras.api._v2.keras 2.2.4-tf


In [9]:
with tf.device("cpu"):
    a = tf.constant([1])
with tf.device("gpu"):
    b = tf.constant([1])
    

In [10]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [11]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [16]:
with tf.device("gpu"):
    c = tf.constant([1])
with tf.device("gpu"):
    d = tf.constant([1])

In [17]:
d.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [18]:
tf.is_tensor(a)

True

In [19]:
a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
tf.convert_to_tensor(a)

<tf.Tensor: id=202020019, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [26]:
tf.convert_to_tensor(a,dtype="float32")

<tf.Tensor: id=202020023, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [27]:
tf.zeros([3,4])

<tf.Tensor: id=202020027, shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [28]:
tf.zeros((3,4))

<tf.Tensor: id=202020031, shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [8]:
a = tf.constant(1.0, dtype="float64")
print(a)

tf.Tensor(1.0, shape=(), dtype=float64)


In [12]:
b = tf.constant([1], dtype='float32')
print(b)

tf.Tensor([1.], shape=(1,), dtype=float32)


In [14]:
b.shape

TensorShape([1])

In [17]:
a.shape

TensorShape([])

In [20]:
c = tf.constant([[1, 3],[4,5]])
print(c)

tf.Tensor(
[[1 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [21]:
c.shape

TensorShape([2, 2])

In [22]:
tf.rank(c)

<tf.Tensor: id=18, shape=(), dtype=int32, numpy=2>

In [25]:
c.ndim

2

In [28]:
c.numpy()

array([[1, 3],
       [4, 5]], dtype=int32)

In [30]:
c.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [31]:
c.gpu()
c.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [33]:
tf.is_tensor(c)

True

In [34]:
isinstance(a, tf.Tensor)

True

In [35]:
d = np.array([1,2,3,4,5,6])
print(d)

[1 2 3 4 5 6]


In [40]:
e = tf.convert_to_tensor(d, dtype='int32')
print(e)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [44]:
tf.cast(a, dtype='float32')

<tf.Tensor: id=33, shape=(), dtype=float32, numpy=1.0>

In [108]:
a

<tf.Tensor: id=8, shape=(), dtype=float64, numpy=1.0>

In [88]:
tf.cast(a, dtype='float32')

<tf.Tensor: id=118, shape=(), dtype=float32, numpy=1.0>

In [102]:
a.dtype == tf.float32

False

In [110]:
w = tf.Variable(a)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=1.0>


In [112]:
v = tf.Variable(a, name='input_data')
print(v)
print(v.name)

<tf.Variable 'input_data:0' shape=() dtype=float64, numpy=1.0>
input_data:0


In [113]:
a

<tf.Tensor: id=8, shape=(), dtype=float64, numpy=1.0>

In [116]:
a1 = int(a)
print(a1)

1


In [122]:
a_zeros = tf.zeros([4,5])
print(a_zeros)
a.device

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32)


'/job:localhost/replica:0/task:0/device:CPU:0'

In [125]:
c

<tf.Tensor: id=16, shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5]], dtype=int32)>

In [132]:
c_zeros = tf.zeros_like(c)
print(c_zeros)

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)


In [136]:
fill_33 = tf.fill([3,3], 33)
print(fill_33)

tf.Tensor(
[[33 33 33]
 [33 33 33]
 [33 33 33]], shape=(3, 3), dtype=int32)


In [139]:
n_normal = tf.random.normal([5,6], mean=1, stddev=1)
print(n_normal)

tf.Tensor(
[[ 0.70337725 -0.08034194  0.8596723   0.43456537  0.7149936   1.4278154 ]
 [-0.3918084   1.6822131   2.459505    3.434417   -0.1844871   1.9440072 ]
 [ 1.5556796   2.2739124   0.8123861   0.6963445   1.149748    0.4440264 ]
 [ 0.7745478   1.9207492   1.0738423   1.6524363   0.21622163  0.32024962]
 [ 1.1707705   1.3991807   2.1274972   1.530839    0.5293553   1.8043473 ]], shape=(5, 6), dtype=float32)


In [141]:
n_truncated_nomal = tf.random.truncated_normal([5,6], mean=1, stddev=1)
print(n_truncated_nomal)

tf.Tensor(
[[ 1.474896    2.254323    1.0386856   0.9179516  -0.21136725  0.16397429]
 [ 1.361259    1.1637095   0.8215121   1.5382066   1.7864676   2.787969  ]
 [ 0.49191505  1.1732568  -0.09710288  0.6081341  -0.384848    1.3074772 ]
 [ 0.35180008  1.7527413   1.2702451   0.49989408  0.54338074  1.6245409 ]
 [ 1.0482545   2.9401398   1.3530071   1.4171478   0.1618985   0.9949649 ]], shape=(5, 6), dtype=float32)


In [144]:
n_uniform = tf.random.uniform([3,4], minval=0, maxval=9)
print(n_uniform)

tf.Tensor(
[[1.3653764 8.024578  5.2055035 0.7908397]
 [6.6401806 1.8228089 4.2119503 0.3461219]
 [3.855857  8.38316   4.1115913 5.0069494]], shape=(3, 4), dtype=float32)


In [147]:
idx = tf.range(10)
idx

<tf.Tensor: id=301, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [152]:
idx_shuffle = tf.random.shuffle(idx)
print(idx)
print(idx_shuffle)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([2 1 6 8 7 4 5 9 0 3], shape=(10,), dtype=int32)


In [153]:
tf.constant(3)

<tf.Tensor: id=317, shape=(), dtype=int32, numpy=3>

In [5]:
# tf.Tensor(3)  error
tf.constant(3)

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=3>

In [6]:
tf.convert_to_tensor(3)

<tf.Tensor: id=2, shape=(), dtype=int32, numpy=3>

In [7]:
tf.constant(3) == tf.convert_to_tensor(3)

False

In [8]:
tf.constant(4)

<tf.Tensor: id=6, shape=(), dtype=int32, numpy=4>

In [10]:
tf.constant(3)

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=3>

In [12]:
out = tf.random.uniform([4, 10])
print(out)

tf.Tensor(
[[0.58192825 0.4441316  0.5365665  0.23704779 0.09800708 0.48431945
  0.43820488 0.00446427 0.5858636  0.28659105]
 [0.382468   0.00354159 0.10155427 0.68656254 0.69130766 0.92967105
  0.4008571  0.7659757  0.75113904 0.8983675 ]
 [0.9606875  0.4584309  0.7853116  0.44686925 0.21490848 0.94847584
  0.5496007  0.12485802 0.26849926 0.8592037 ]
 [0.7387645  0.18077993 0.7882881  0.8683318  0.8679855  0.3506105
  0.8231     0.2181468  0.00934386 0.67861104]], shape=(4, 10), dtype=float32)


In [14]:
y = tf.range(4)
print(y)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [15]:
y = tf.one_hot(y, depth=10)
print(y)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [16]:
loss = tf.keras.losses.mse(y, out)
print(loss)

tf.Tensor([0.15777169 0.5081766  0.34526283 0.32791978], shape=(4,), dtype=float32)


In [18]:
loss = tf.reduce_mean(loss)
print(loss)

tf.Tensor(0.33478272, shape=(), dtype=float32)


In [2]:
x = tf.random.normal([4,784])
print(x)

tf.Tensor(
[[ 0.10443728  1.2801687  -0.23216695 ...  0.80439675  1.1140157
   1.0587333 ]
 [ 1.0187948   0.03112094  1.1506449  ...  0.12827285  0.29840344
   0.917894  ]
 [ 1.1875043  -0.10716313  1.7397226  ... -0.779188   -0.00649513
   0.8584696 ]
 [ 0.4888877  -0.261347   -1.2615181  ... -1.2040375  -1.236744
  -0.18150787]], shape=(4, 784), dtype=float32)


In [4]:
# net = layers.Dense(10)
# print(net)

In [50]:
(X_train, y_train), (X_test, y_test) = keras.datasets.imdb.load_data(num_words=10000)

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [10]:
a = tf.ones([2,3])
print(a)
            

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
a = tf.ones([1, 5, 5, 3])
print(a)

tf.Tensor(
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]], shape=(1, 5, 5, 3), dtype=float32)


In [28]:
b = tf.random.normal([2, 5, 5, 3])
print(b)

tf.Tensor(
[[[[ 3.10895234e-01 -1.26896060e+00 -3.54110688e-01]
   [-6.32619619e-01  1.54743052e+00 -9.55180466e-01]
   [-6.22351468e-02  6.21351004e-01  8.35139453e-01]
   [ 6.81369841e-01  9.31581020e-01 -2.51025587e-01]
   [ 3.47420275e-01 -1.67274404e+00 -8.65048885e-01]]

  [[-6.90393925e-01 -3.15040559e-01  4.82325226e-01]
   [-1.88991427e-01 -4.68526065e-01 -1.27619818e-01]
   [-1.82653952e+00 -1.30312383e+00  3.97615880e-01]
   [ 7.92686164e-01 -1.43179607e+00 -1.17613029e+00]
   [ 7.44081378e-01  4.72910963e-02  5.91657698e-01]]

  [[ 3.39996628e-02 -1.30321220e-01  1.90495229e+00]
   [ 9.45936680e-01  1.49150699e-01  1.23115146e+00]
   [ 1.25650728e+00 -1.38695765e+00  3.57499450e-01]
   [ 3.47335547e-01  1.14517592e-01  1.13764882e+00]
   [ 1.23576272e+00  5.08791506e-01  1.13927341e+00]]

  [[-1.03230977e+00 -6.45955324e-01  1.93762705e-01]
   [-1.21309996e+00 -2.05808640e+00  6.70870066e-01]
   [-1.19686306e+00 -9.91902947e-01  1.82318196e-01]
   [ 1.25728559e+00  3.013827

In [40]:
b[0,:,0,0]

<tf.Tensor: id=268, shape=(5,), dtype=float32, numpy=
array([ 0.31089523, -0.6903939 ,  0.03399966, -1.0323098 ,  0.19458418],
      dtype=float32)>

In [42]:
b[0,0:5:,0,0]

<tf.Tensor: id=278, shape=(5,), dtype=float32, numpy=
array([ 0.31089523, -0.6903939 ,  0.03399966, -1.0323098 ,  0.19458418],
      dtype=float32)>

In [34]:
b[0][1][2][2]

<tf.Tensor: id=235, shape=(), dtype=float32, numpy=0.39761588>

In [36]:
b[1,2,3]
b[1,2,3].shape

TensorShape([3])

In [37]:
b[:,:,4,2]

<tf.Tensor: id=253, shape=(2, 5), dtype=float32, numpy=
array([[-0.8650489 ,  0.5916577 ,  1.1392734 ,  0.02992471, -1.3430228 ],
       [ 0.6307501 ,  2.1283484 ,  0.19370796, -0.17652191,  0.41795006]],
      dtype=float32)>

In [39]:
b[:,:,:,1]

<tf.Tensor: id=263, shape=(2, 5, 5), dtype=float32, numpy=
array([[[-1.2689606 ,  1.5474305 ,  0.621351  ,  0.931581  ,
         -1.672744  ],
        [-0.31504056, -0.46852607, -1.3031238 , -1.4317961 ,
          0.0472911 ],
        [-0.13032122,  0.1491507 , -1.3869576 ,  0.11451759,
          0.5087915 ],
        [-0.6459553 , -2.0580864 , -0.99190295,  0.30138275,
         -0.40043092],
        [ 1.4403701 , -1.9950982 , -0.46431392,  1.7352234 ,
         -0.11125505]],

       [[ 0.7805685 ,  1.6811112 ,  0.14602165, -0.04388177,
         -0.7199159 ],
        [ 1.0783283 ,  0.53417724,  0.3775445 , -0.20034888,
          0.7305767 ],
        [ 0.9388957 ,  0.19600524,  0.03099099, -0.40478894,
          0.6927728 ],
        [-0.5835873 , -0.40916315, -0.5215613 , -1.0260053 ,
          0.19011456],
        [ 1.4904562 ,  0.44865614,  0.7062097 , -0.07265037,
         -0.27656767]]], dtype=float32)>

In [43]:
c = tf.range(10)
print(c)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [45]:
c[::-1]

<tf.Tensor: id=293, shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [47]:
c[::-2]

<tf.Tensor: id=303, shape=(5,), dtype=int32, numpy=array([9, 7, 5, 3, 1], dtype=int32)>

In [48]:
c[1:8:-1]

<tf.Tensor: id=308, shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [49]:
c[8:1:-1]

<tf.Tensor: id=313, shape=(7,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2], dtype=int32)>

In [51]:
scores = tf.random.normal([2,3,5])
print(scores)

tf.Tensor(
[[[-0.5130746  -1.2741175   0.8170308   0.3738894   0.24757713]
  [ 0.41276228 -0.5406671  -1.1023306   1.6622264   1.3292588 ]
  [ 0.7704178   1.8180676  -0.9471904  -0.09689624 -1.786463  ]]

 [[ 0.48072973 -0.03934016 -0.93775815 -0.10460647 -1.2790611 ]
  [-0.00878148  0.61874473  2.3965242  -0.6543708  -2.142612  ]
  [-0.5091969  -0.32294616  0.8613772   0.0030089   0.25330767]]], shape=(2, 3, 5), dtype=float32)


In [52]:
tf.gather(scores, axis=1, indices=[0,2])

<tf.Tensor: id=331, shape=(2, 2, 5), dtype=float32, numpy=
array([[[-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,
          0.24757713],
        [ 0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624,
         -1.786463  ]],

       [[ 0.48072973, -0.03934016, -0.93775815, -0.10460647,
         -1.2790611 ],
        [-0.5091969 , -0.32294616,  0.8613772 ,  0.0030089 ,
          0.25330767]]], dtype=float32)>

In [53]:
print(scores)

tf.Tensor(
[[[-0.5130746  -1.2741175   0.8170308   0.3738894   0.24757713]
  [ 0.41276228 -0.5406671  -1.1023306   1.6622264   1.3292588 ]
  [ 0.7704178   1.8180676  -0.9471904  -0.09689624 -1.786463  ]]

 [[ 0.48072973 -0.03934016 -0.93775815 -0.10460647 -1.2790611 ]
  [-0.00878148  0.61874473  2.3965242  -0.6543708  -2.142612  ]
  [-0.5091969  -0.32294616  0.8613772   0.0030089   0.25330767]]], shape=(2, 3, 5), dtype=float32)


In [56]:
tf.gather_nd(scores, [0])

<tf.Tensor: id=341, shape=(3, 5), dtype=float32, numpy=
array([[-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,  0.24757713],
       [ 0.41276228, -0.5406671 , -1.1023306 ,  1.6622264 ,  1.3292588 ],
       [ 0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624, -1.786463  ]],
      dtype=float32)>

In [57]:
tf.gather_nd(scores, [0, 1])

<tf.Tensor: id=344, shape=(5,), dtype=float32, numpy=
array([ 0.41276228, -0.5406671 , -1.1023306 ,  1.6622264 ,  1.3292588 ],
      dtype=float32)>

In [58]:
tf.gather_nd(scores, [0,1,2])

<tf.Tensor: id=347, shape=(), dtype=float32, numpy=-1.1023306>

In [59]:
tf.gather_nd(scores, [[0,1,2]])

<tf.Tensor: id=350, shape=(1,), dtype=float32, numpy=array([-1.1023306], dtype=float32)>

In [60]:
a = scores
print(a)

tf.Tensor(
[[[-0.5130746  -1.2741175   0.8170308   0.3738894   0.24757713]
  [ 0.41276228 -0.5406671  -1.1023306   1.6622264   1.3292588 ]
  [ 0.7704178   1.8180676  -0.9471904  -0.09689624 -1.786463  ]]

 [[ 0.48072973 -0.03934016 -0.93775815 -0.10460647 -1.2790611 ]
  [-0.00878148  0.61874473  2.3965242  -0.6543708  -2.142612  ]
  [-0.5091969  -0.32294616  0.8613772   0.0030089   0.25330767]]], shape=(2, 3, 5), dtype=float32)


In [61]:
a[0,0]

<tf.Tensor: id=356, shape=(5,), dtype=float32, numpy=
array([-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,  0.24757713],
      dtype=float32)>

In [62]:
a

<tf.Tensor: id=327, shape=(2, 3, 5), dtype=float32, numpy=
array([[[-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,
          0.24757713],
        [ 0.41276228, -0.5406671 , -1.1023306 ,  1.6622264 ,
          1.3292588 ],
        [ 0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624,
         -1.786463  ]],

       [[ 0.48072973, -0.03934016, -0.93775815, -0.10460647,
         -1.2790611 ],
        [-0.00878148,  0.61874473,  2.3965242 , -0.6543708 ,
         -2.142612  ],
        [-0.5091969 , -0.32294616,  0.8613772 ,  0.0030089 ,
          0.25330767]]], dtype=float32)>

In [64]:
tf.boolean_mask(a, mask=[[False, False, True],[True, False, False]])

<tf.Tensor: id=386, shape=(2, 5), dtype=float32, numpy=
array([[ 0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624, -1.786463  ],
       [ 0.48072973, -0.03934016, -0.93775815, -0.10460647, -1.2790611 ]],
      dtype=float32)>

In [65]:
a

<tf.Tensor: id=327, shape=(2, 3, 5), dtype=float32, numpy=
array([[[-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,
          0.24757713],
        [ 0.41276228, -0.5406671 , -1.1023306 ,  1.6622264 ,
          1.3292588 ],
        [ 0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624,
         -1.786463  ]],

       [[ 0.48072973, -0.03934016, -0.93775815, -0.10460647,
         -1.2790611 ],
        [-0.00878148,  0.61874473,  2.3965242 , -0.6543708 ,
         -2.142612  ],
        [-0.5091969 , -0.32294616,  0.8613772 ,  0.0030089 ,
          0.25330767]]], dtype=float32)>

In [67]:
tf.reshape(a, [2,15])

<tf.Tensor: id=391, shape=(2, 15), dtype=float32, numpy=
array([[-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,  0.24757713,
         0.41276228, -0.5406671 , -1.1023306 ,  1.6622264 ,  1.3292588 ,
         0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624, -1.786463  ],
       [ 0.48072973, -0.03934016, -0.93775815, -0.10460647, -1.2790611 ,
        -0.00878148,  0.61874473,  2.3965242 , -0.6543708 , -2.142612  ,
        -0.5091969 , -0.32294616,  0.8613772 ,  0.0030089 ,  0.25330767]],
      dtype=float32)>

In [68]:
a

<tf.Tensor: id=327, shape=(2, 3, 5), dtype=float32, numpy=
array([[[-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,
          0.24757713],
        [ 0.41276228, -0.5406671 , -1.1023306 ,  1.6622264 ,
          1.3292588 ],
        [ 0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624,
         -1.786463  ]],

       [[ 0.48072973, -0.03934016, -0.93775815, -0.10460647,
         -1.2790611 ],
        [-0.00878148,  0.61874473,  2.3965242 , -0.6543708 ,
         -2.142612  ],
        [-0.5091969 , -0.32294616,  0.8613772 ,  0.0030089 ,
          0.25330767]]], dtype=float32)>

In [70]:
tf.reshape(a, [2, -1])

<tf.Tensor: id=396, shape=(2, 15), dtype=float32, numpy=
array([[-0.5130746 , -1.2741175 ,  0.8170308 ,  0.3738894 ,  0.24757713,
         0.41276228, -0.5406671 , -1.1023306 ,  1.6622264 ,  1.3292588 ,
         0.7704178 ,  1.8180676 , -0.9471904 , -0.09689624, -1.786463  ],
       [ 0.48072973, -0.03934016, -0.93775815, -0.10460647, -1.2790611 ,
        -0.00878148,  0.61874473,  2.3965242 , -0.6543708 , -2.142612  ,
        -0.5091969 , -0.32294616,  0.8613772 ,  0.0030089 ,  0.25330767]],
      dtype=float32)>

In [2]:
who

keras	 module	 mpl	 np	 os	 pd	 plt	 sklearn	 sys	 
tf	 time	 


In [3]:
a = tf.random.normal([4, 35, 8])
a.shape

TensorShape([4, 35, 8])

In [5]:
tf.gather(a, axis=1, indices=[2,1,4,0]).shape

TensorShape([4, 4, 8])

In [10]:
tf.gather_nd(a, [0,1,2]).shape
tf.gather_nd(a,[0,1,2])

<tf.Tensor: id=26, shape=(), dtype=float32, numpy=-0.72075576>

In [12]:
tf.gather_nd(a,[[0,1,2]])

<tf.Tensor: id=32, shape=(1,), dtype=float32, numpy=array([-0.72075576], dtype=float32)>

In [13]:
a.shape

TensorShape([4, 35, 8])

In [14]:
tf.reshape(a, [4, -1]).shape

TensorShape([4, 280])

In [15]:
a.shape

TensorShape([4, 35, 8])

In [20]:
tf.transpose(a, perm=[0, 2, 1]).shape

TensorShape([4, 8, 35])

In [22]:
tf.expand_dims(a, axis=-1).shape

TensorShape([4, 35, 8, 1])

In [23]:
tf.squeeze(tf.expand_dims(a, axis=-1)).shape

TensorShape([4, 35, 8])

In [24]:
a.shape

TensorShape([4, 35, 8])

In [55]:
b = tf.random.uniform([4, 999, 3500])
e = tf.random.normal([4, 3500, 999])
f = b@e
f.shape

TensorShape([4, 999, 999])

In [26]:
c = a@b
c.shape

TensorShape([4, 35, 35])

In [36]:
e = tf.random.normal([4, 3500, 9999])

In [37]:
f = b@e
f.shape

TensorShape([4, 999, 999])

In [62]:
# tf.math.log(8)

InternalError: Could not find valid device for node.
Node: {{node Log}}
All kernels registered for op Log :
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='XLA_GPU'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BFLOAT16, DT_HALF]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
 [Op:Log]

In [6]:
tf.exp(2.)

<tf.Tensor: id=9, shape=(), dtype=float32, numpy=7.389056>

In [67]:
1e-3

0.001

In [70]:
n = np.nan

In [71]:
n

nan

In [5]:
a = tf.constant(1.)
tf.exp(a)

<tf.Tensor: id=6, shape=(), dtype=float32, numpy=2.7182817>

In [11]:
tf.math.log(8.)

<tf.Tensor: id=21, shape=(), dtype=float32, numpy=2.0794415>

In [12]:
a = tf.ones([2, 2])

In [13]:
a

<tf.Tensor: id=25, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [19]:
a = tf.random.normal([4, 2, 4], 2.)
b = tf.random.uniform([4, 5], 3.)
# print(a.shape, b.shape)
b1 = tf.broadcast_to(b,[4, 4, 5])
# print(a.shape, b1.shape)
c = a@b1
c.shape

TensorShape([4, 2, 5])

## The forward propagation

In [2]:
(x, y), _ = datasets.mnist.load_data()
print(x.shape, y.shape)

(60000, 28, 28) (60000,)


In [4]:
x = tf.convert_to_tensor(x, dtype=tf.float32) / 255.
y = tf.convert_to_tensor(y, dtype=tf.int32)


print(x.shape, y.shape)
print(x.dtype, y.dtype)
print(tf.reduce_min(x), tf.reduce_max(x))
print(tf.reduce_min(y), tf.reduce_max(y))

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run RealDiv: Dst tensor is not initialized. [Op:RealDiv] name: truediv/

In [105]:
train_db = tf.data.Dataset.from_tensor_slices((x,y)).batch(128)
print(train_db)


<BatchDataset shapes: ((None, 28, 28), (None,)), types: (tf.float32, tf.int32)>


In [106]:
train_iter = iter(train_db)
sample = next(train_iter)
print('batch:', sample[0].shape, sample[1].shape)

batch: (128, 28, 28) (128,)


In [107]:
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev = 0.1))
b1 = tf.Variable(tf.zeros([256]))
w2 = tf.Variable(tf.random.truncated_normal([256,128], stddev = 0.1))
b2 = tf.Variable(tf.zeros([128]))
w3 = tf.Variable(tf.random.truncated_normal([128,10], stddev = 0.1))
b3 = tf.Variable(tf.zeros([10]))
lr = 1e-3


In [108]:
# for step,(x, y) in enumerate(train_db):
#     print(step)
# step: 1~468

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [109]:
# print(60000 / 128)

468.75


In [110]:
for epoch in range(10):
    for step, (x, y) in enumerate(train_db):
        x = tf.reshape(x, [-1, 28*28])
        with tf.GradientTape() as tape:
            h1 = x@w1 + tf.broadcast_to(b1, [x.shape[0], 256])
            h1 = tf.nn.relu(h1)
            h2 = h1@w2 + b2
            h2 = tf.nn.relu(h2)

            out = h2@w3 + b3
            y_onehot = tf.one_hot(y, depth=10)

            loss = tf.square(y_onehot - out)
            loss = tf.reduce_mean(loss)

        grads = tape.gradient(loss, [w1, b1, w2, b2, w3, b3])
    #     w1 = w1 - lr * grads[0]
    #     b1 = b1 - lr * grads[1]
    #     w2 = w2 - lr * grads[2]
    #     b2 = b2 - lr * grads[3]
    #     w3 = w3 - lr * grads[4]
    #     b3 = b3 - lr * grads[5]
        w1.assign_sub(lr * grads[0])
        b1.assign_sub(lr * grads[1])
        w2.assign_sub(lr * grads[2])
        b2.assign_sub(lr * grads[3])
        w3.assign_sub(lr * grads[4])
        b3.assign_sub(lr * grads[5])


        if step % 100 == 0:
            print(step, 'loss', float(loss))

0 loss 0.29109659790992737
100 loss 0.18036219477653503
200 loss 0.16927555203437805
300 loss 0.15281584858894348
400 loss 0.15805715322494507
0 loss 0.15843629837036133
100 loss 0.14280782639980316
200 loss 0.13806039094924927
300 loss 0.12959778308868408
400 loss 0.1365964263677597
0 loss 0.13652126491069794
100 loss 0.12679409980773926
200 loss 0.12054536491632462
300 loss 0.11581878364086151
400 loss 0.12307663261890411
0 loss 0.12214203923940659
100 loss 0.11609084904193878
200 loss 0.10891725867986679
300 loss 0.10651291906833649
400 loss 0.11389607191085815
0 loss 0.11168640851974487
100 loss 0.10841190814971924
200 loss 0.10071176290512085
300 loss 0.09971769899129868
400 loss 0.10698749870061874
0 loss 0.10379087924957275
100 loss 0.10252754390239716
200 loss 0.09456586837768555
300 loss 0.09449092298746109
400 loss 0.10158327966928482
0 loss 0.09762454032897949
100 loss 0.09785718470811844
200 loss 0.08968953043222427
300 loss 0.09028662741184235
400 loss 0.09716002643108368


In [111]:
who

a	 b	 b1	 b2	 b3	 c	 datasets	 epoch	 grads	 
h1	 h2	 keras	 loss	 lr	 module	 mpl	 np	 os	 
out	 pd	 plt	 sample	 sklearn	 step	 sys	 tape	 tf	 
time	 train_db	 train_iter	 type	 w1	 w2	 w3	 x	 y	 
y_onehot	 


In [7]:
a = tf.random.uniform([5,4], maxval=5, dtype=tf.int32)
print(a)

tf.Tensor(
[[0 2 4 4]
 [0 0 2 4]
 [0 0 3 4]
 [2 3 4 4]
 [3 4 0 3]], shape=(5, 4), dtype=int32)


In [8]:
tf.reshape(a[:3], [-1])

<tf.Tensor: id=32, shape=(12,), dtype=int32, numpy=array([0, 2, 4, 4, 0, 0, 2, 4, 0, 0, 3, 4], dtype=int32)>

In [10]:
shape = tf.constant([4,4,4])
shape

<tf.Tensor: id=36, shape=(3,), dtype=int32, numpy=array([4, 4, 4], dtype=int32)>

In [12]:
print(shape)

tf.Tensor([4 4 4], shape=(3,), dtype=int32)


In [19]:
shape[1].shape

TensorShape([])