### Data loading

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import datasets

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.0.0-alpha0
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
matplotlib 3.1.0
numpy 1.16.4
pandas 0.24.2
sklearn 0.21.2
tensorflow 2.0.0-alpha0
tensorflow.python.keras.api._v2.keras 2.2.4-tf


In [2]:
(X, y), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(X.shape, y.shape, x_test.shape, y_test.shape)

(60000, 28, 28) (60000,) (10000, 28, 28) (10000,)


In [4]:
y[:4]

array([5, 0, 4, 1], dtype=uint8)

In [5]:
y_test[:4]

array([7, 2, 1, 0], dtype=uint8)

In [6]:
y_onehot = tf.one_hot(y, depth=10)
y_onehot[:4]

<tf.Tensor: id=8, shape=(4, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
(X_cifar, y_cifar), (x_test_cifar, y_test_cifar) = keras.datasets.cifar10.load_data()

170500096/170498071 [==============================] - 42s 0us/step


In [8]:
print(X_cifar.shape, y_cifar.shape, x_test_cifar.shape, y_test_cifar.shape)

(50000, 32, 32, 3) (50000, 1) (10000, 32, 32, 3) (10000, 1)


In [17]:
print(type(X_cifar), type(y_cifar), type(x_test_cifar), type(y_test_cifar))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [18]:
db_test_cifar = tf.data.Dataset.from_tensor_slices((x_test_cifar, y_test_cifar))

In [20]:
# db_test_cifar
print(db_test_cifar)
next(iter(db_test_cifar))[0]

<TensorSliceDataset shapes: ((32, 32, 3), (1,)), types: (tf.uint8, tf.int64)>


<tf.Tensor: id=34, shape=(32, 32, 3), dtype=uint8, numpy=
array([[[158, 112,  49],
        [159, 111,  47],
        [165, 116,  51],
        ...,
        [137,  95,  36],
        [126,  91,  36],
        [116,  85,  33]],

       [[152, 112,  51],
        [151, 110,  40],
        [159, 114,  45],
        ...,
        [136,  95,  31],
        [125,  91,  32],
        [119,  88,  34]],

       [[151, 110,  47],
        [151, 109,  33],
        [158, 111,  36],
        ...,
        [139,  98,  34],
        [130,  95,  34],
        [120,  89,  33]],

       ...,

       [[ 68, 124, 177],
        [ 42, 100, 148],
        [ 31,  88, 137],
        ...,
        [ 38,  97, 146],
        [ 13,  64, 108],
        [ 40,  85, 127]],

       [[ 61, 116, 168],
        [ 49, 102, 148],
        [ 35,  85, 132],
        ...,
        [ 26,  82, 130],
        [ 29,  82, 126],
        [ 20,  64, 107]],

       [[ 54, 107, 160],
        [ 56, 105, 149],
        [ 45,  89, 132],
        ...,
        [ 24,  7

In [21]:
next(iter(db_test_cifar))[1]

<tf.Tensor: id=42, shape=(1,), dtype=int64, numpy=array([3])>

In [22]:
(x_fashion, y_fashion), (x_val_fashion, y_val_fashion) = datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 2s 1us/step


In [23]:
print(x_fashion.shape, y_fashion.shape, x_val_fashion.shape, y_val_fashion.shape)

(60000, 28, 28) (60000,) (10000, 28, 28) (10000,)
