### 20190615

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import datasets

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.0.0-alpha0
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
matplotlib 3.1.0
numpy 1.16.4
pandas 0.24.2
sklearn 0.21.2
tensorflow 2.0.0-alpha0
tensorflow.python.keras.api._v2.keras 2.2.4-tf


In [2]:
y = tf.constant([1, 2, 3, 0, 2])
y_onehot = tf.one_hot(y, depth=4)
y_float32 = tf.cast(y_onehot, dtype=tf.float32)

out = tf.random.normal([5, 4])


In [4]:
loss1 = tf.reduce_mean(tf.square(y_float32 - out))

In [7]:
loss1

<tf.Tensor: id=14, shape=(), dtype=float32, numpy=1.2301543>

In [9]:
tf.losses.MSE(y_float32, out)

<tf.Tensor: id=23, shape=(5,), dtype=float32, numpy=
array([1.321346  , 0.80357057, 0.26360798, 1.4749372 , 2.2873096 ],
      dtype=float32)>

In [10]:
tf.reduce_mean(tf.losses.MSE(y_float32, out))

<tf.Tensor: id=29, shape=(), dtype=float32, numpy=1.2301543>

In [15]:
x = tf.random.normal([2, 784])
w = tf.random.normal([784, 3])
b = tf.zeros([3])

In [16]:
out = x@w + b
out

<tf.Tensor: id=69, shape=(2, 3), dtype=float32, numpy=
array([[-29.193142 ,  44.712227 ,   8.142887 ],
       [ 16.221962 ,  -5.7150574, -36.90502  ]], dtype=float32)>

In [17]:
out_prob = tf.math.softmax(out)
out_prob

<tf.Tensor: id=71, shape=(2, 3), dtype=float32, numpy=
array([[8.0040130e-33, 1.0000000e+00, 1.3126155e-16],
       [1.0000000e+00, 2.9708008e-10, 8.4575418e-24]], dtype=float32)>

In [18]:
out_prob1 = tf.math.softmax(out, axis=1)
out_prob1

<tf.Tensor: id=73, shape=(2, 3), dtype=float32, numpy=
array([[8.0040130e-33, 1.0000000e+00, 1.3126155e-16],
       [1.0000000e+00, 2.9708008e-10, 8.4575418e-24]], dtype=float32)>

In [20]:
tf.reduce_sum(out_prob1, axis=1)

<tf.Tensor: id=79, shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [23]:
tf.constant(1.)

<tf.Tensor: id=81, shape=(), dtype=float32, numpy=1.0>

In [24]:
x = tf.random.normal([2, 4])
w = tf.random.normal([4, 3])
b = tf.zeros([3])
y = tf.constant([2, 0])

In [27]:
tf.one_hot(y, depth=3)

<tf.Tensor: id=114, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 1.],
       [1., 0., 0.]], dtype=float32)>

In [25]:
prob = tf.nn.softmax(x@w + b, axis=1)
prob

<tf.Tensor: id=101, shape=(2, 3), dtype=float32, numpy=
array([[0.8740752 , 0.04976668, 0.07615812],
       [0.05964647, 0.90267575, 0.03767786]], dtype=float32)>

In [26]:
tf.losses.MSE(tf.one_hot(y, depth=3), prob)

<tf.Tensor: id=109, shape=(2,), dtype=float32, numpy=array([0.5399893 , 0.56683594], dtype=float32)>

In [33]:
y1 = tf.constant([[0.8, 0.1, 0.1], [0.1, 0.7, 0.2]])
y1

<tf.Tensor: id=161, shape=(2, 3), dtype=float32, numpy=
array([[0.8, 0.1, 0.1],
       [0.1, 0.7, 0.2]], dtype=float32)>

In [34]:
print(tf.losses.MSE(tf.one_hot(y, depth=3), y1))
print(tf.one_hot(y,depth=3))
print(y1)

tf.Tensor([0.48666668 0.44666663], shape=(2,), dtype=float32)
tf.Tensor(
[[0. 0. 1.]
 [1. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.8 0.1 0.1]
 [0.1 0.7 0.2]], shape=(2, 3), dtype=float32)


In [35]:
tf.reduce_mean(tf.losses.MSE(tf.one_hot(y, depth=3), y1))

<tf.Tensor: id=185, shape=(), dtype=float32, numpy=0.46666664>

In [36]:
(0.4867 + 0.4467)/2

0.4667

In [ ]:
with tf.GradientTape() as tape:
    tape.watch(w, b)
    prob = tf.nn.softmax(x@w + b, axis=1)
    