### GradientTape
20190614 15:29

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import datasets

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.0.0-alpha0
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
matplotlib 3.1.0
numpy 1.16.4
pandas 0.24.2
sklearn 0.21.2
tensorflow 2.0.0-alpha0
tensorflow.python.keras.api._v2.keras 2.2.4-tf


In [3]:
a = tf.random.normal([2, 3, 4])
print(a)

tf.Tensor(
[[[-0.26207426 -0.9296764   0.412411   -1.1298676 ]
  [-1.0596776   0.18312262  0.7390484  -0.6497675 ]
  [ 0.22243372  1.0766287  -1.6152761  -0.2391422 ]]

 [[ 0.18956281 -0.17823678 -0.2280936  -0.70154464]
  [-0.25630635 -1.5102234   0.8779353  -0.5350999 ]
  [ 0.92523783 -1.509075    0.7692771   0.5579545 ]]], shape=(2, 3, 4), dtype=float32)


In [4]:
a_sigmoid = tf.sigmoid(a)
print(a_sigmoid)

tf.Tensor(
[[[0.43485388 0.2829904  0.60166585 0.24418554]
  [0.25737107 0.54565316 0.67678773 0.34304193]
  [0.5553803  0.74585545 0.1658574  0.44049776]]

 [[0.5472493  0.4555584  0.44322255 0.33146986]
  [0.4362719  0.18090573 0.7063942  0.3693282 ]
  [0.71610814 0.18107593 0.6833645  0.6359791 ]]], shape=(2, 3, 4), dtype=float32)


In [5]:
w = tf.constant(1.)
x = tf.constant(2.)
y = x*w

In [13]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch([w])
    y2 = x*w
grad2 = tape.gradient(y2, [w])
    
    
grad2

[<tf.Tensor: id=47, shape=(), dtype=float32, numpy=2.0>]

In [28]:
grad2 = tape.gradient(y2, [w])

---

In [29]:
w = tf.Variable(1.)
b = tf.Variable(2.)
x = tf.Variable(3.)

with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        y = x * w + b
    dy_dw, dy_db = t2.gradient(y, [w, b])
    
d2y_dw2 = t1.gradient(dy_dw, w)

print(dy_dw)
print(dy_db)
print(d2y_dw2)

assert dy_dw.numpy() == 3.0
assert d2y_dw2 is None

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
None
