### Top-k Accuracy

In [38]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import datasets

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.0.0-alpha0
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
matplotlib 3.1.0
numpy 1.16.4
pandas 0.24.2
sklearn 0.21.2
tensorflow 2.0.0-alpha0
tensorflow.keras 2.2.4-tf


In [39]:
tf.random.set_seed(2467)

In [44]:
def accuracy(output, target, topk=(1,)):
    maxk = max(topk)
    batch_size = target.shape[0]
    
    pred = tf.math.top_k(output, maxk).indices
    pred = tf.transpose(pred, perm=[1, 0])
    target_ = tf.broadcast_to(target, pred.shape)
    
    correct = tf.equal(pred, target_)
    
    res = []
    for k in topk:
    #     print(print(acc)k)
        correct_k = tf.cast(tf.reshape(correct[:k],[-1]),dtype=tf.float32)
        correct_k = tf.reduce_sum(correct_k)
        acc = float(correct_k* (100.0 / batch_size))
        res.append(acc)
        
    return res


In [47]:
output = tf.random.normal([10, 6])
output = tf.math.softmax(output, axis=1)
target = tf.random.uniform([10], maxval=6, dtype=tf.int32)
print('prob:  ', pred.numpy())
pred = tf.argmax(output, axis=1)
print('pred:  ', pred.numpy())
print('label: ', target.numpy())

acc = accuracy(output, target, topk=(1,2,3,4,5,6))
print('top-1-6', acc)

prob:   [2 5 4 0 5 5 2 0 3 4]
pred:   [1 0 5 4 5 5 0 1 5 3]
label:  [2 5 3 2 0 5 5 2 3 1]
top-1-6 [10.0, 10.0, 40.0, 70.0, 90.0, 100.0]


In [2]:
# def accuracy(output, target, topk=(1,)):
output = tf.constant([[0.2, 0.3, 0.5],[0.01, 0.8, 0.19],[0.7, 0.2, 0.1]])
print(output)

tf.Tensor(
[[0.2  0.3  0.5 ]
 [0.01 0.8  0.19]
 [0.7  0.2  0.1 ]], shape=(3, 3), dtype=float32)


In [3]:
target = tf.constant([2, 2, 1])
print(target)

tf.Tensor([2 2 1], shape=(3,), dtype=int32)


In [4]:
topk = (1, 2, 3)
print(topk, type(topk))

(1, 2, 3) <class 'tuple'>


In [5]:
maxk = max(topk)
print(maxk)

3


In [6]:
batch_size = target.shape[0]
print(batch_size)

3


In [10]:
pred = tf.math.top_k(output, maxk).indices
print(pred)

tf.Tensor(
[[2 1 0]
 [1 2 0]
 [0 1 2]], shape=(3, 3), dtype=int32)


In [11]:
pred = tf.transpose(pred, perm=[1, 0])
print(pred)

tf.Tensor(
[[2 1 0]
 [1 2 1]
 [0 0 2]], shape=(3, 3), dtype=int32)


In [12]:
target_ = tf.broadcast_to(target, pred.shape)
print(target_)

tf.Tensor(
[[2 2 1]
 [2 2 1]
 [2 2 1]], shape=(3, 3), dtype=int32)


In [36]:
correct = tf.equal(pred, target_)
print(correct)

tf.Tensor(
[[ True False False]
 [False  True  True]
 [False False False]], shape=(3, 3), dtype=bool)


In [20]:
tf.reshape(correct[:3],[-1])

<tf.Tensor: id=48, shape=(9,), dtype=bool, numpy=array([ True, False, False, False,  True,  True, False, False, False])>

In [34]:
correct_k = tf.cast(tf.reshape(correct[:3],[-1]),dtype=tf.float32)
print(correct_k)

tf.Tensor([1. 0. 0. 0. 1. 1. 0. 0. 0.], shape=(9,), dtype=float32)


In [35]:
batch_size

3

In [26]:
print(topk)

(1, 2, 3)


In [29]:
res = []
for k in topk:
#     print(print(acc)k)
    correct_k = tf.cast(tf.reshape(correct[:k],[-1]),dtype=tf.float32)
    correct_k = tf.reduce_sum(correct_k)
    acc = float(correct_k / batch_size)
    res.append(acc)
    print(acc)
    

0.3333333432674408
1.0
1.0
